### ISSUE TITLE
프로젝트 자랑 상세 페이지 좋아요 버튼기능

### ISSUE THREAD

**Issue by zzzissu** [PKNU-JavaStudy/mozip_backend#51]
## 어떤 기능인가요?

> 프로젝트 자랑을 했을 때 해당 게시물을 좋아요 하면 비동기적으로 좋아요 개수가 추가되고, 이미 좋아요 된 게시물을 눌렀을때에는 좋아요가 감소하는 기능

## 작업 상세 내용

- [x] 좋아요 버튼을 클릭했을 때 해당 게시물의 좋아요 수를 증감 시키기 
- [x]  Likes테이블에 memberId와 projectId의 존재 여부에 따라 증감
- [x] 해당 게시물에 같은 아이디를 가진 사람이 좋아요를 누르면 좋아요 취소

**Comment by LegdayDev** [comment]
좋아요 버튼 숫자 CSS
